- visualization/plot_points.py
- visualization/risk_map.py
Wrote a script that plots point-level data on a Leaflet map using Folium.  Not sure how useful this is but hopefully it at least serves as a starting point for visualizing point-level data on a slippy map.  
Usage is pretty similar to the script for mapping model predictions, it takes two named arguments on the command line:
-n = name of layer
-f = dataset filename
> Add script for mapping point-level data

- src/data/ATR_scraping/geocode_snap_ATRs.py
script now imputes data between segments with scraped ATR values
> edited script for KNN imputation

- reports/css/style.css
- reports/historical_crash_map.html
- reports/js/make_plots.js
- reports/js/update_map.js
Pushing so that our repo is synced up with the version of the mvp that is hosted on Firebase. Main functionality change was implementing the ability to compare predictions for two different weeks.
> Map comparison feature

- environment.yml
- environment_docker.yml
- src/data/config.yml
- src/data/config_addfeats.yml
- src/data/config_cambridge.yml
- src/data/config_dc.yml
- src/data/create_segments.py
- src/data/join_segments_crash_concern.py
- src/data/make_dataset_osm.py
- src/data/util.py
- src/features/make_canon_dataset.py
Add ability to pass different in concern files, and adds a DC specific config file
> V0 analysis

- src/data/config_cambridge.yml
- src/data/make_dataset_osm.py
- src/features/make_canon_dataset.py
Get make canonical running with cambridge see click fix data
> Fixed date_cols to be generalizable in make_canonical

- Dockerfile
- README.md
moving to miniconda3 base image (python 3.6 by default)
update Docker docs
> docker upgrades

- .travis.yml
Fix .travis.yml so codecov will run on pipeline and initialize_city
> Fix codecov to run on files in src

- src/data/osm_create_maps.py
I accidentally checked in a couple of lines I didn't mean to in osm_create_maps to help with my debugging. Fixing this
> Undo debugging changes

- src/README.md
- src/features/make_canon_dataset.py
- src/features/tests/test_make_canon.py
- src/models/tests/test_train_model.py
- src/models/train_model.py
Skip features that are in a city's config file but don't exist in the dataset.
Also small update to README based on a question someone had in running the pipeline.
> Missing feature bugfix

- src/data_standardization/standardize_crashes.py
- src/features/make_canon_dataset.py
One bug fix, and one update to a warning message
> Small changes

- .travis.yml
This fixes the failing test on travis
> Use newer version of ubuntu for travis

- src/visualization/risk_map.py
Just made a minor change to make the risk map smaller and faster to generate.
> removed excess data from risk map

- src/README.md
My bad! Didn't see @j-t-t 's comment.
> Revert "Update README.md"

- .travis.yml
- azure-pipelines.yml
- environment.yml
- environment_linux.yml
- environment_pc.yml
- src/data/TMC_scraping/parse_tmc.py
- src/data/create_segments.py
- src/data/osm_create_maps.py
- src/data/propagate_volume.py
- src/data/record.py
- src/data/tests/test_osm_create_maps.py
- src/data/tests/test_util.py
- src/data/util.py
- src/tools/make_map_subset.py
- src/tools/tests/test_make_map_subset.py
Fixing this issue: https://github.com/Data4Democracy/crash-model/issues/282
Also updated some pinning because of broken conda
> Pyproj perf

- src/config/config_buffalo.yml
Adding the Buffalo config file.
> adding Buffalo, NY config file

- src/pipeline.py
Take risk_map out of the pipeline steps
> Remove risk_map from pipeline

- environment_linux.yml
- environment_mac.yml
- src/config/config_somerville.yml
- src/data/README.md
- src/data/TMC_scraping/parse_tmc.py
- src/data/geocoding_util.py
- src/data/propagate_volume.py
- src/data/tests/test_initialize_city.py
- src/data/util.py
- src/data_standardization/boston_volume.py
- src/data_standardization/standardize_crashes.py
- src/data_standardization/tests/test_standardize_crashes.py
- src/initialize_city.py
- src/showcase/static/config.js
- src/tools/geocode_batch.py
Updating Somerville's config file and the js config file to add Somerville
Side issue: there is a weird bug in fiona at the moment such that if you import fiona the geocoder doesn't work for mapbox. Since I needed to geocode Somerville's data, that was a roadblock, so I pulled all of the geocoding-specific functionality out of util.py into geocoding_util.py and updated all the associated calls
> Add Somerville

- Dockerfile
Minor fix here, just changing the dockerfile to use the environment_linux.yml.  Then it works fine with the instructions in the README.
> change dockerfile environment

- src/models/tests/test_train_model.py
- src/models/train_model.py
Some fixes/additions:
- Automatic removal of features that have no information (i.e. only one possible value).  
- Fix for features in the linear model
- Test for process features
> fix for uninformative features and general fix for features

- .github/workflows/main.yml
- environment.yml
- environment_linux.yml
- environment_mac.yml
- environment_pc.yml
- src/README.md
- src/features/tests/test_make_canon.py
Update to more recent pinned versions, and add mac and windows tests
> update conda pinned versions

- src/showcase/static/update_map.js
Fix the slider that filters for speed limit and risk score
> Fix filtering for Boston

- src/config/config_boise.yml
- src/config/config_meridian.yml
Let me know where is the most appropriate place to share data!
> Onboarding boise
